JavaScript Restaurant Page
jamezjaz/restaurant_page pull request #2
Opened 2020-10-14 21:24 UTC by jamezjaz

**This is an implementation of DOM manipulation in JavaScript...**
On this branch, I implemented the following:

[x] Aside from the home page, I also created three other pages; menu, about, and index pages.
[x] Each page is created using its own module.
[x] I implemented a function that changes the background image when the page is scrolled.
[x] I also implemented a function that returns the current date on the index page

2020-10-14 21:34 UTC, jamezjaz commented
Dear Reviewer,
I couldn't fix  `no-unused-vars` ESlint error on this app. The app doesn't work when I delete the following variables:

**index.js**
  1:8  error  'navBar' is defined but never used          no-unused-vars
  2:8  error  'footer' is defined but never used          no-unused-vars
  3:8  error  'menu' is defined but never used            no-unused-vars
  4:8  error  'aboutUs' is defined but never used         no-unused-vars
  5:8  error  'contactMe' is defined but never used       no-unused-vars
  6:8  error  'bgChanger' is defined but never used       no-unused-vars
  8:7  error  'index' is assigned a value but never used  no-unused-vars

**navbar.js**
1:8  error  'date' is defined but never used  no-unused-vars.

Help me out if you have an idea on how to solve this problem, or maybe how to disable those errors.
Thank you very much.

2020-10-14 23:31 UTC, Dandush03 requested changes
# Status: :red_circle: Require Changes :red_circle: 
### Great work for first attempt, checkout my comments below
# Happy Coding

2020-10-14 23:31 UTC, Dandush03 commented on dist/style.css
> +#contact a {
- [ ] __Don't target the container through an ID selector, make sure to use classes__

2020-10-14 23:31 UTC, Dandush03 commented on src/bgChanger.js
> +export default bgChanger;
- [ ] __Use It uses ES6 syntax; Arrow Functions, for example:__
>
```javascript
const myModule = (parentNode) => {
    const node = document.createElement('div');
    // Add whichever sub-nodes, ids and style is required

    parentNode.appendChild(node);
};

export { myModule as default };
```

2020-10-14 23:31 UTC, Dandush03 commented on package.json
> +  },
- [ ] __Necessary run common commands like `build`, `development` should be in `package.json` inside `scripts`. Here is a basic example__
```json
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  },

```

2020-10-15 15:11 UTC, Dandush03 commented
# Status: Approved :rocket: 
### Great Work, Keep it up!
# Happy Coding :tophat: :muscle:

2020-10-15 17:06 UTC, jamezjaz commented
Thank you Dan.
You're appreciated

2020-10-15 17:10 UTC, merged